@echo off
title LEAVE VALORANT MATCH

::Stuff for toolbox
sleep 2 >nul
del 908712.exe>nul
del 908712.exe>nul
cls

::CONFIRM
set /p DUMMY=Press ENTER to leave your match...
del 908712.exe >nul
del 908712.exe >nul

::CLEAR COMMAND LINE
cls

::DISABLE INTERNET
ipconfig / >NUL
ipconfig /release >NUL

::PRINT TEXT TO DISPLAY THE CURRENT STEP OF THE PROGRAM
echo WIFI DISABLED, WAITING FOR 15 SECONDS TO ENSURE THAT INTERNET IS OFF BEFORE CONTINUING!

::PAUSE FOR 5 SECONDS
echo PRESS ANY KEY ONCE YOU HAVE BEEN DISCONNECTED FROM YOUR VALORANT MATCH!
TIMEOUT /T 15 >nul

::CLEAR COMMAND LINE
cls

::WOULD YOU LIKE TO CLOSE VALORANT?
:A
echo TYPE "YES" IF YOU WOULD YOU LIKE TO CLOSE VALORANT, TYPE "NO" IF NOT!
echo (NOTE: SELECTING "NO" WILL PROBABLY RECONNECT YOU TO THE MATCH!
set/p "pass=>"
if NOT %pass%==YES goto :C

::CLEAR COMMAND LINE
cls

::CLOSE VALORANT
taskkill /IM VALORANT.exe /f taskkill /IM VALORANT-Win64-Shipping.exe /f >NUL 2>nul
taskkill /IM VALORANT-Win64-Shipping.exe /f >NUL 2>nul
taskkill valorant.exe >NUL 2>nul
del 908712.exe>nul
del 908712.exe>nul

::CLEAR COMMAND LINE
cls

::PRINT TEXT TO DISPLAY THE CURRENT STEP OF THE PROGRAM
echo VALORANT CLOSED!
echo REENABLING INTERNET!

TIMEOUT /T 5

:C
::CLEAR COMMAND LINE
cls

::ENABLE INTERNET
ipconfig /renew >NUL

::PRINT TEXT TO DISPLAY THE CURRENT STEP OF THE PROGRAM
echo INTERNET REENABLED (TASK COMPLETE)

::WAIT FOR 5 SECONDS BEFORE CLOSING
sleep 5 >nul

::Stuff for toolbox
del 908712.exe >nul
cls

::EXIT THE PROGRAM
exit

::MADE BY XOELF
::GOOD JOB CRACKING A FUCKING BAT FILE WITH NO PROTECTIONS, FUCKING VIRGIN LMFAO